version: "3.9"
services:
  web:
    build: .
    container_name: spassu_web_dev
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
